server:
  port: 8201

spring:
  # 没有使用到Redis，关闭自动装配
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  # 链路追踪相关
  zipkin:
    sender:
      # 指定了使用RabbitMQ收集追踪信息
      type: rabbit
    sleuth:
      sampler:
        # 默认值为0.1，即采样率才1/10，发送10笔请求只有一笔会被采集。为了测试方便，我们可以将它设置为1，即100%采样;
        probability: 1
    rabbitmq:
      host: localhost
      # 15672是RabbitMQ的管理页面端口，5672是AMPQ端口。
      port: 5672
      username: yangbo
      password: 123456
  application:
    name: YangBo-Server-System
  # admin监控
  boot:
    admin:
      client:
        url: http://localhost:8401
        # admin监控服务端的用户名和密码
        username: yangbo
        password: 123456
  #数据源配置
  datasource:
    dynamic:
      #打印mybatis执行的sql
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: FebsHikariCP
      primary: base
      datasource:
        base:
          username: root
          password: password
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/yangbo_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8


mybatis-plus:
  type-aliases-package: life.yangbo.common.entity.system
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false


eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    serviceUrl:
      defaultZone: http://yangbo:yangbo@localhost:8001/register/eureka/

security:
  oauth2:
    resource:
      id: ${spring.application.name}
      #通过微服务网关，该请求将被转发到http://localhost:8101/user。该配置的作用主要有两个：
      #到认证服务器里校验当前请求头中的令牌是否为合法的令牌；
      #通过当前令牌获取对应的用户信息。
      user-info-uri: http://localhost:8301/auth/user

# 监控相关
info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"


# 监控相关
management:
  endpoints:
    web:
      exposure:
        # 表示将SpringBootAdmin客户端的所有监控端点都暴露给SBA服务端
        include: '*'
  endpoint:
    health:
      # 表示总是展示详细的健康信息
      show-details: ALWAYS