server:
  port: 8201

spring:
  application:
    name: YangBo-Server-System
  # 由于引用了common的mybatis-plus-boot-starter会自动装配，这儿不需要需要手动关闭
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    serviceUrl:
      defaultZone: http://yangbo:yangbo@localhost:8001/register/eureka/

security:
  oauth2:
    resource:
      id: ${spring.application.name}
      # 通过微服务网关，该请求将被转发到http://localhost:8101/user。该配置的作用主要有两个：
      # 到认证服务器里校验当前请求头中的令牌是否为合法的令牌；
      # 通过当前令牌获取对应的用户信息。
      user-info-uri: http://localhost:8301/auth/user
