server:
  port: 8301
spring:
  application:
    name: Yangbo-Gateway
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: yangbo
        password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8001
    gateway:
      routes:
        # 路由ID，保存唯一即可
        - id: YangBo-Auth
          # load balance；注册中心的名称
          uri: lb://YangBo-Auth
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: authfallback
                # 如果响应时间超过timeoutInMilliseconds设定的时间，则进入到gateway的控制器/fallback/YangBo-Auth
                fallbackUri: forward:/fallback/YangBo-Auth

        - id: YangBo-Server-System
          uri: lb://YangBo-Server-System
          predicates:
            - Path=/system/**
          filters:
            - name: Hystrix
              args:
                name: systemfallback
                fallbackUri: forward:/fallback/YangBo-Server-System
        - id: YangBo-Server-test
          uri: lb://YangBo-Server-Test
          predicates:
            - Path=/test/**
          filters:
            - name: Hystrix
              args:
                name: testfallback
                fallbackUri: forward:/fallback/YangBo-Server-Test
      default-filters:
        # 请求转发前，将Path的内容截去前面一位。比如/auth/hello会被截取为/hello。
        - StripPrefix=1


management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,info,gateway

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 超时时间
            timeoutInMilliseconds: 3000