server:
  port: 8202

spring:
  application:
    name: YangBo-Server-Test
  # 由于引用了common的mybatis-plus-boot-starter会自动装配，这儿不需要需要手动关闭
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://yangbo:yangbo@localhost:8001/register/eureka/
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:8301/auth/user

feign:
  hystrix:
    # 开启熔断机制，feign发生异常时fallback生效
    enabled: true

hystrix:
  # 配置把SecurityContext对象从你当前主线程传输到Hystrix线程;让feign拦截器顺利获取令牌
  shareSecurityContext: true