server:
  port: 8001
  servlet:
    context-path: /register

spring:
  application:
    name: YangBo-Register
  security:
    user:
      name: yangbo
      password: yangbo
  # admin监控
  boot:
    admin:
      client:
        url: http://localhost:8401
        # admin监控服务端的用户名和密码
        username: yangbo
        password: 123456

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        # 表示将SpringBootAdmin客户端的所有监控端点都暴露给SBA服务端
        include: '*'
  endpoint:
    health:
      # 表示总是展示详细的健康信息
      show-details: ALWAYS

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 30
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/

